# Generated by Django 4.1.3 on 2022-12-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='prodefault.jpg', upload_to='store/image'),
        ),
    ]
